# Generated by Django 4.2.4 on 2023-09-02 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_onion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onion',
            old_name='titulo',
            new_name='pagina',
        ),
    ]
